// Builds the Rust tectonics engine (engine/) to WebAssembly and embeds it as
// base64 in src/engine/tecto-wasm.ts, so the web app builds without Rust.
//   npm run engine
// Needs: rustup target add wasm32-unknown-unknown
// (If the target's prebuilt std isn't installable, set BUILD_STD=1 to build
// std from source: needs the rust-src component and nightly features.)
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const env = { ...process.env };
let cmd = 'cargo build --release --target wasm32-unknown-unknown';
if (process.env.BUILD_STD) {
  env.RUSTC_BOOTSTRAP = '1';
  cmd += ' -Zbuild-std=std,panic_abort';
}
execSync(cmd, { cwd: 'engine', stdio: 'inherit', env });
const wasm = readFileSync('engine/target/wasm32-unknown-unknown/release/tecto.wasm');
const b64 = wasm.toString('base64');
const lines = [];
for (let i = 0; i < b64.length; i += 120) lines.push(`  '${b64.slice(i, i + 120)}',`);
writeFileSync(
  'src/engine/tecto-wasm.ts',
  `// Generated by scripts/build-engine.mjs from engine/ — do not edit.\n` +
    `// ${wasm.length} bytes of WebAssembly.\n` +
    `export const TECTO_WASM_BASE64 = [\n${lines.join('\n')}\n].join('');\n`,
);
console.log(`embedded ${wasm.length} bytes → src/engine/tecto-wasm.ts`);
